-- MySQL Script generated by MySQL Workbench
-- Wed 06 Jan 2021 10:26:02 PM EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fizzbizDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fizzbizDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fizzbizDb` DEFAULT CHARACTER SET utf8 ;
USE `fizzbizDb` ;

-- -----------------------------------------------------
-- Table `fizzbizDb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fizzbizDb`.`users` (
  `username` VARCHAR(40) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` TEXT(900) NOT NULL,
  `mobileTel` VARCHAR(14) NOT NULL,
  `workTel` VARCHAR(14) NULL,
  `profileImage` VARCHAR(300) NOT NULL,
  `continent` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `townCity` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `DOB` VARCHAR(40) NOT NULL,
  `facebook` VARCHAR(800) NULL,
  `instagram` VARCHAR(800) NULL,
  `linkedln` VARCHAR(800) NULL,
  `twitter` VARCHAR(800) NULL,
  `youtube` VARCHAR(800) NULL,
  `github` VARCHAR(800) NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `fizzbizDb`.`businessCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fizzbizDb`.`businessCategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `maincategory` VARCHAR(100) NOT NULL,
  `subcategory` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `onlinestores_UNIQUE` (`maincategory` ASC),
  UNIQUE INDEX `shoppingcenter_UNIQUE` (`subcategory` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fizzbizDb`.`businessApp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fizzbizDb`.`businessApp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `businessName` VARCHAR(200) NOT NULL,
  `brandIcon` VARCHAR(300) NOT NULL,
  `mission` TEXT(1200) NOT NULL,
  `businessEmail` VARCHAR(200) NOT NULL,
  `businessType` VARCHAR(45) NOT NULL,
  `continent` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `townCity` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `range` VARCHAR(45) NOT NULL,
  `businessCategory` INT NOT NULL,
  `shortIntro` TEXT(300) NOT NULL,
  `shortTopic` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `businessEmail_UNIQUE` (`businessEmail` ASC),
  UNIQUE INDEX `brandIcon_UNIQUE` (`brandIcon` ASC),
  UNIQUE INDEX `businessName_UNIQUE` (`businessName` ASC),
  INDEX `fk_businessApp_1_idx` (`businessCategory` ASC),
  CONSTRAINT `fk_businessApp_1`
    FOREIGN KEY (`businessCategory`)
    REFERENCES `fizzbizDb`.`businessCategories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fizzbizDb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fizzbizDb`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serviceName` VARCHAR(45) NOT NULL,
  `serviceIcon` VARCHAR(300) NULL,
  `serviceDesc` TEXT(1000) NOT NULL,
  `price` DECIMAL NOT NULL,
  `businessId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_1_idx` (`businessId` ASC),
  CONSTRAINT `fk_services_1`
    FOREIGN KEY (`businessId`)
    REFERENCES `fizzbizDb`.`businessApp` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fizzbizDb`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fizzbizDb`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `businessAppID` INT NOT NULL,
  `continent` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `townCity` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locations_1_idx` (`businessAppID` ASC),
  CONSTRAINT `fk_locations_1`
    FOREIGN KEY (`businessAppID`)
    REFERENCES `fizzbizDb`.`businessApp` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fizzbizDb`.`businessImages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fizzbizDb`.`businessImages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `businessAppID` INT NOT NULL,
  `imageLink` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_1_idx` (`businessAppID` ASC),
  UNIQUE INDEX `imageLink_UNIQUE` (`imageLink` ASC),
  CONSTRAINT `fk_images_1`
    FOREIGN KEY (`businessAppID`)
    REFERENCES `fizzbizDb`.`businessApp` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fizzbizDb`.`businessVideos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fizzbizDb`.`businessVideos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `businessVideoLink` VARCHAR(300) NOT NULL,
  `businessAppID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_businessVideos_1_idx` (`businessAppID` ASC),
  CONSTRAINT `fk_businessVideos_1`
    FOREIGN KEY (`businessAppID`)
    REFERENCES `fizzbizDb`.`businessApp` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fizzbizDb`.`businessSocialMedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fizzbizDb`.`businessSocialMedia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `businessSocialMediaLink` VARCHAR(300) NOT NULL,
  `socialName` VARCHAR(45) NOT NULL,
  `businessAppID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_businessSocialMedia_1_idx` (`businessAppID` ASC),
  CONSTRAINT `fk_businessSocialMedia_1`
    FOREIGN KEY (`businessAppID`)
    REFERENCES `fizzbizDb`.`businessApp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fizzbizDb`.`ownerBusiness`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fizzbizDb`.`ownerBusiness` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) NOT NULL,
  `businessAppID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ownerBusiness_1_idx` (`username` ASC),
  INDEX `fk_ownerBusiness_2_idx` (`businessAppID` ASC),
  CONSTRAINT `fk_ownerBusiness_1`
    FOREIGN KEY (`username`)
    REFERENCES `fizzbizDb`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ownerBusiness_2`
    FOREIGN KEY (`businessAppID`)
    REFERENCES `fizzbizDb`.`businessApp` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fizzbizDb`.`businessReviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fizzbizDb`.`businessReviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `businessReviews` TEXT(1000) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `businessAppID` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
